### ISSUE TITLE
示例语言最好换一下

### ISSUE THREAD

**Issue by ifredom** [suragch/mongol#1]
用蒙语做示例，看不懂文字，所以也不知道文字的左右方向和上下方向。何不用中文。 用古时候的写法。

古文的顺序：
从上到下书写，从右到左书写。

小 天
心 干
火 物
烛 燥
。 ,

**Comment by suragch** [comment]
@ifredom Sorry for the long delay in replying. I wasn't getting notifications before. This project isn't set up to display the ancient Chinese text in right-to-left line wrapping, but if you clone the repository it would be relatively little work to implement that. Mostly it would just involve changing the logic of `MongolParagraph.draw` method. (https://github.com/suragch/mongol/blob/master/lib/src/base/mongol_paragraph.dart)

**Comment by suragch** [comment]
Another option is to use a Wrap widget with the following settings:

```dart
textDirection: TextDirection.rtl,
direction: Axis.vertical,
```

https://medium.com/flutter-community/flutter-wrap-widget-e1ee0b005b16

**Comment by ifredom** [comment]
> 另一种选择是使用具有以下设置的 Wrap 小部件：
> 
> ```dart
> textDirection ： TextDirection .rtl，
> 方向： 轴。垂直，
> ```
> 
> https://medium.com/flutter-community/flutter-wrap-widget-e1ee0b005b16

Thank you for your work. This problem has been solved
