### ISSUE TITLE
from right to left

### ISSUE THREAD

**Issue by 251143259** [suragch/mongol#11]
Do you support text from right to left？
请问支持文本从右往左吗？

**Comment by suragch** [comment]
When rendered, all text is laid out from top to bottom and line wraps from left to right. If you are talking about right to left line wrapping for Chinese, this is not supported, but see my comment [here](https://github.com/suragch/mongol/issues/1#issuecomment-850358062).

**Comment by 251143259** [comment]
Thanks, I tried to modify mongol_paragraph.dart
