### ISSUE TITLE
Please export mongol_text_painter.dart

### ISSUE THREAD

**Issue by roberthook823** [suragch/mongol#19]
I would like you to export mogol_text_painter.dart file.
I am developing image editing app by this package, but I cannot use mongol_text_painter. So I customized the main.dart file but I don't want to customize original package because this package is upgraded continuously. Please export the mogol_text_painter.dart next version.

**Comment by suragch** [comment]
Sure. It is exported now in version 3.0.1. 

Let me know if it is working for you.

**Comment by roberthook823** [comment]
It is working now. Thank you for your help.

**Comment by roberthook823** [comment]
I didn't know you'd fix it this quickly. Thank you for quick fixing.

**Comment by suragch** [comment]
You're welcome. This kind of fix is pretty easy to make.
