### ISSUE TITLE
The mongolian conent cannot render correctly on iOS simulator

### ISSUE THREAD

**Issue by vicxia** [suragch/mongol#2]
![企业微信20200705224245](https://user-images.githubusercontent.com/4124906/86535165-e294b580-bf10-11ea-832e-407e38ff84b0.png)

My environment: mac os big sur, iOS13.5 simulator, xcode11.5, AndroidStudio3.6.3

The mongolian conent cannot render correctly on iOS simulator, but did render correctly on android simulator.

What's difference between iOS and android platform? Can this problem be solved?

**Comment by suyie001** [comment]
@vicxia  you need to set a mongolian font.

**Comment by suragch** [comment]
Sorry, I apparently wasn't getting notifications for issues before. Suyie is correct. You can solve this problem by adding a Mongolian font (as described the repo's readme). However, I would have expected iOS's default font to work too. I'm not sure why that is happening.
