### ISSUE TITLE
Please export the mongol_render_editable.dart

### ISSUE THREAD

**Issue by Satsrag** [suragch/mongol#31]
I am developing an embedded Mongolian Input Method with this package on the desktop. Use the `Focus` widget to intercept the keyboard event. However, the candidate widget follows the `Cursor` and gets the `Cursor` location by using `mongol_render_editable.dart` . Please export the `mongol_render_editable.dart` next version.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/17843861/197327127-bf4ee397-de65-44b2-a3b5-3eadf8a453b1.png">

**Comment by suragch** [comment]
Done in version 3.2.0.
