### ISSUE TITLE
输入框换行后有空格导致顶部不齐

### ISSUE THREAD

**Issue by maxiaodegithub** [suragch/mongol#36]
输入内容后自动换行和手动换行后，第二列往后头部都会有一个空格，导致第一列跟后面的列对不齐。

**Comment by suragch** [comment]
能加个截图吗?

**Comment by maxiaodegithub** [comment]
![image](https://user-images.githubusercontent.com/19525713/226506799-510a046e-e10b-431c-8e7a-f7a5e55e1390.png)
这种特殊字符的情况错位该怎么处理？

**Comment by maxiaodegithub** [comment]
![image](https://user-images.githubusercontent.com/19525713/226506945-5245c79d-243b-4e56-a57b-fb61442a92fa.png)
这种包含特殊字符的情况，改怎么对齐

**Comment by suragch** [comment]
那是什么字符？ 可以发文字版吗？我想测试一下

**Comment by maxiaodegithub** [comment]
试试这段文字
（ ᠬᠥᠮᠥᠨ ᠎ᠳ᠋ᠦ᠍ ᠪᠠᠷᠢᠵᠤ ᠵᠣᠯᠭᠠᠵᠤ ᠪᠣᠯᠣᠨ᠎ᠠ） ᠱᠢᠷ᠎ᠠ ᠦᠩᠭᠡ︱ ᠱᠢᠷ᠎ᠠ ᠨᠠᠷᠠᠨ᠂ ᠠᠯᠢᠪᠠ ᠮᠠᠭᠤ
ᠪᠥᠬᠥᠨ ᠎ᠢ ᠵᠠᠢᠯᠠᠭᠤᠯᠬᠤ ᠎ᠶᠢᠨ ᠪᠡᠯᠭᠡᠳᠡᠯ （ ᠵᠥᠪᠬᠡᠨ ᠪᠠᠭᠱᠢ ᠳᠠᠭᠠᠨ ᠯᠠ ᠪᠠᠷᠢᠵᠤ ᠪᠣᠯᠣᠨ᠎ᠠ）

suragch ***@***.***> 于2023年3月21日周二 12:56写道：

**Comment by suragch** [comment]
我无法重现问题。 这是直接添加到示例应用程序中的样子：

<img width="500" alt="Screen Shot 2023-03-22 at 17 30 35" src="https://user-images.githubusercontent.com/10300220/226861561-e6f97a84-af01-4991-a3ea-4628c31c9507.png">

可以在一个简单的 flutter 项目中重现问题吗？

**Comment by maxiaodegithub** [comment]
是字体的原因导致的不能对齐的问题。
