### ISSUE TITLE
Breaking changes with Flutter 3.13

### ISSUE THREAD

**Issue by suragch** [suragch/mongol#46]
There are quite errors after upgrading to Flutter 3.13.

Eventually I will work on fixing these but these few days I have some other work I need to finish first. If anyone wants to work on the errors first, please let me know.

**Comment by suragch** [comment]
I've updated the package to 6.0.0, which I believe fixes the breaking changes with Flutter 3.13. The existing tests pass and the example demo app appears to work the same as it did before.

@Satsrag When you get a change, can you check that the update also works for you.

**Comment by Satsrag** [comment]
@suragch I test about `shortcuts` and [TextInputControl](https://api.flutter.dev/flutter/services/TextInputControl-mixin.html).
Everything is ok. Thank you!

**Comment by suragch** [comment]
@Satsrag Thanks for checking! Closing this issue then.
