### ISSUE TITLE
Why two keyboard demos?

### ISSUE THREAD

**Issue by suragch** [suragch/mongol#52]
The demo app has two keyboard demos:

- keyboard_demo.dart
- text_input_control_keyboard_demo.dart

Do we need both of them? Can they be combined into one and still demonstrate the important information?

**Comment by Satsrag** [comment]
text_input_control_keyboard_demo.dart is just for testing customizing `TextInputControl` is working. Added by #42. I think we delete keyboard_demo.dart. customizing `TextInputControl` is Flutter's official way to make the embedded Keyboard. I make an embedded Mongol keyboard by customizing `TextInputControl`, [this](https://github.com/Satsrag/embed_input)

**Comment by suragch** [comment]
Ok, great. I'll delete the original keyboard_demo.dart and rename yours to keyboard_demo.
